### ISSUE TITLE
updateInterval only working for first embedded element on page

### ISSUE THREAD

**Issue by HeiDan** [Tom-Hirschberger/MMM-EmbedURL#9]
I'm using the embed-url plugin multiple times in my magic mirror config which works like a charm. Thanks for providing this plugin.

The only thing that is not working for me are the "refreshes of the plugins"
I recognized that only the first occurrence of the embed-url plugin is refreshed with "updateInterval" setting. All the other embeds are not updated at all.

E.g.:
``    {
   	module: "MMM-EmbedURL",
    position: "bottom_left",
			header: "test1",
			config: {
			  updateInterval: 120,
			  attributes: [
				  "frameborder=0",
				  "allowfullscreen"
			  ],
			  classes: "test",
			  embed: [
				  "https://myUrl.com",
			  ]
			}
		},
		{
			module: "MMM-EmbedURL",
			position: "bottom_left",
			header: "test2",
			config: {
			  updateInterval: 120,
			  attributes: [
				  "frameborder=0",
				  "allowfullscreen"
			  ],
			  classes: "test",
			  embed: [
				   "https://myUrl2.com",
			  ]
			}
		},
``

In this sample only the first "iframe" (https://myUrl.com) is refreshed after 120 seconds. The second iframe https://myUrl2.com is never refreshed.

**Comment by Tom-Hirschberger** [comment]
Hi,

i created a simple PHP which shows the time when it is loaded and added three instances of it to my mirror.
In my case `updateInterval` works as expected but the problem is that the browser caches the results and displays the same time for all instances.
As a result i released version 0.0.5 of the module a few seconds ago which provides a new option `appendTimestamp` that causes a timestamp being added to the embedded URLs. The browser then ignores the cache and fetches the page as excepted.
Can you try the new version with the `appendTimestamp` option set to `true` and check if your problem is still present?

**Comment by HeiDan** [comment]
Hi,
Wow, such a fast response and quick solution. Thanks a lot it works perfectly.
Have a great evening and thanks for this very useful extension.

**Comment by Tom-Hirschberger** [comment]
Thank you and you are welcome.
Feel free to ask if there are other problems.
